### ISSUE TITLE
lich compatibility module

### ISSUE THREAD

**Issue by ondreian** [ondreian/norn.rb#14]
we need to detect that the user is launching a `.lic` script and shim in all the missing api calls as best as possible.  Some of these will be impossible to get 100% correct, but good enough for reliability should be a goal.

**Comment by robojase** [comment]
Do you want to document which function calls are needed here, to help with the process? There's also going to be need to translate whatever data norn will provide to something compatible with lich objects, if you're looking to provide greater resolution

**Comment by robojase** [comment]
Also, is there any good documentation on the scripting engine for Norn (Or is that Olib?) and what commands it provides? If so, I can start to map out some of the obvious call translations, or try to get some of the commonly used commands in Lich scripts I've envountered

**Comment by ondreian** [comment]
Olib is just Lich stuff. Norn will eventually superceded it for me.

Documentation definitely needs to be my next goal before I add anymore new code. 

All of the modules/classes for interacting with the world live in /lib/world/

**Comment by ondreian** [comment]
I'm going to close this issue for now, it's an interesting concept, but I'm not sure we can do it in a deterministic way.  

It maybe a nice long-term goal, but I'd rather work on making the core as strong as possible first.
